title: NoroStudy
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

url: https://ngrow.dev
twitter_username: Ngrow_
github_username:  ngocro208
name: Ro Ngoc Vo
description: Web Developer from Somewhere
avatar: https://avatars2.githubusercontent.com/u/33742348?s=460&v=4
paginate: 8
paginate_path: "/page:num/"


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Site Author
author:
  name             : "Ro Ngoc Vo"
  avatar           : "https://avatars2.githubusercontent.com/u/33742348?s=460&v=4"
  bio              : "Just another crazy things, running, traveling .."
  location         : "Danang, Vietnam"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:ngocro208@gmail.com
    - label: "Ngrow"
      icon: "fas fa-fw fa-link"
      url: "https://ngrow.dev"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Ngrow_"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ngocro208"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/noro.vo"

facebook:
  app-id: 2138296316441824


github: [metadata]

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-github-metadata
  - jemoji
  - jekyll-gist


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME
